import java.io.*;

class Check {
    void check(int age) throws InterruptedException {
        if (age < 18) {
            throw new InterruptedException("Input output error");
        } else {
            System.out.println("You are eligible for vote");
        }
    }
}

class ageCheckException {
    public static void main(String[] args) throws InterruptedException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        Check ec = new Check();
        int x = 0;
        System.out.println("Enter your age");
        try {
             x = Integer.parseInt(br.readLine());
        } catch (IOException e) {
        }
        ec.check(x);
    }
}
/* Here input output Exception generated by developers(here it is me) */